import { Inter } from 'next/font/google'
import './globals.css'
import { ScaffoldEthAppWithProviders } from '@/components/ScaffoldEthAppWithProviders'
import { ThemeProvider } from "@/components/ThemeProvider";
import { getNonce } from '@/lib/apiClient';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Filecoin Plus Registry',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider enableSystem>
        <ScaffoldEthAppWithProviders>
          {children}
        </ScaffoldEthAppWithProviders>
      </ThemeProvider>
      </body>
    </html>
  )
}
